/**
 * @file sloth.hpp
 * @author ci230846  (clement.introini@cea.fr)
 * @brief List of all header files contained in the kernel directory
 * @version 0.1
 * @date 2024-08-06
 *
 * Copyright CEA (c) 2024
 *
 */
#include "AnalyticalFunctions/AnalyticalFunctions.hpp"
#include "BCs/Boundary.hpp"
#include "BCs/BoundaryConditions.hpp"
#include "Calphad/AnalyticalIdealSolution.hpp"
#include "Calphad/CalphadBase.hpp"
#ifdef SLOTH_USE_LIBTORCH
#include "Calphad/CalphadInformedNeuralNetwork.hpp"
#endif
#include "Calphad/CalphadUtils.hpp"
#include "Calphad/KKS.hpp"
#include "Coefficients/Coefficient.hpp"
#include "Coefficients/Coefficients.hpp"
#include "Coefficients/CommonCoefficients.hpp"
#ifdef SLOTH_USE_EXPRTK
#include "Coefficients/ExprTkSloth.hpp"
#endif
#include "Coefficients/FunctionCoefficient.hpp"
#include "Coefficients/SlothBaseCoefficient.hpp"
#include "Convergence/Convergence.hpp"
#include "Convergence/PhysicalConvergence.hpp"
#include "Couplings/Coupling.hpp"
#include "Glossary/Glossary.hpp"
#include "Integrators/AllenCahnNLFormIntegrator.hpp"
#include "Integrators/BlockAllenCahnNLFormIntegrator.hpp"
#include "Integrators/CahnHilliardNLFormIntegrator.hpp"
#include "Integrators/DiffusionFluxNLFormIntegrator.hpp"
#include "Integrators/DiffusionNLFormIntegrator.hpp"
#include "Integrators/FickNLFormIntegrator.hpp"
#include "Integrators/FourierNLFormIntegrator.hpp"
#include "Integrators/HeatTimeNLFormIntegrator.hpp"
#include "Integrators/MassDiffusionFluxNLFormIntegrator.hpp"
#include "Integrators/MeltingBaseNLFormIntegrator.hpp"
#include "Integrators/MeltingCalphadNLFormIntegrator.hpp"
#include "Integrators/MeltingConstantNLFormIntegrator.hpp"
#include "Integrators/MeltingTemperatureNLFormIntegrator.hpp"
#include "Integrators/SlothGridFunction.hpp"
#include "Integrators/SlothNLFormIntegrator.hpp"
#include "Integrators/ThermalDiffusionFluxNLFormIntegrator.hpp"
#include "Integrators/TimeCHNLFormIntegrator.hpp"
#include "Integrators/TimeNLFormIntegrator.hpp"
#include "Operators/DiffusionOperator.hpp"
#include "Operators/OperatorBase.hpp"
#include "Operators/PhaseFieldOperator.hpp"
#include "Operators/ReducedOperator.hpp"
#include "Operators/SteadyOperatorBase.hpp"
#include "Operators/SteadyReducedOperator.hpp"
#include "Operators/TransientOperatorBase.hpp"
#include "Options/AnalyticalFunctionOptions.hpp"
#include "Options/CalphadOptions.hpp"
#include "Options/DiffusionOptions.hpp"
#include "Options/IntegratorsOptions.hpp"
#include "Options/Options.hpp"
#include "Options/PhaseFieldOptions.hpp"
#include "Options/PhysicalConvergenceOptions.hpp"
#include "Options/PhysicalPropertiesOptions.hpp"
#include "Options/ProblemsOptions.hpp"
#include "Options/SolversOptions.hpp"
#include "Options/SpatialOptions.hpp"
#include "Options/TimeOptions.hpp"
#include "Parameters/Parameter.hpp"
#include "Parameters/Parameters.hpp"
#include "PostProcessing/postprocessing.hpp"
#include "Problems/Calphad_problem.hpp"
#include "Problems/MPIProblem.hpp"
#include "Problems/Problem.hpp"
#include "Problems/ProblemBase.hpp"
#include "Problems/PropertyProblem.hpp"
#include "Property/InterDiffusionCoefficient.hpp"
#include "Property/PropertyBase.hpp"
#include "Solvers/DSolverBase.hpp"
#include "Solvers/HPrecondBase.hpp"
#include "Solvers/HSolverBase.hpp"
#include "Solvers/IPrecondBase.hpp"
#include "Solvers/ISolverBase.hpp"
#include "Solvers/LSolver.hpp"
#include "Solvers/NLSolver.hpp"
#include "Solvers/NLSolverBase.hpp"
#include "Solvers/SlothSolver.hpp"
#include "Solvers/SolverBase.hpp"
#include "Spatial/Spatial.hpp"
#include "Time/Time.hpp"
#include "Utils/Utils.hpp"
#include "Utils/UtilsForData.hpp"
#include "Utils/UtilsForDebug.hpp"
#include "Utils/UtilsForOptions.hpp"
#include "Utils/UtilsForPostProcessing.hpp"
#include "Utils/UtilsForVariants.hpp"
#include "Variables/Variable.hpp"
#include "Variables/Variables.hpp"
