SpatialDiscretization< T, DIM > Class Template Reference
Class for defining the spatial discretization with a mesh coming from a GMSH file or built by using dedicated MFEM methods.
#include </home/ci230846/home-local/MyGitProjects/COMPONENT/PF-MFEM/Spatial/Spatial.hpp>
Public Member Functions
SpatialDiscretization (const std::string &mesh_type, const int &fe_order, const std::string &mesh_file)
template<class... Args>
SpatialDiscretization (const std::string &mesh_type, const int &fe_order, std::tuple< Args... > tup_args)
void set_finite_element_space ()
Set the FE_Collection, the FE_Space and associated size.
mfem::Mesh & get_mesh ()
return a pointer of Mesh
mfem::FiniteElementSpace * get_finite_element_space ()
return a pointer toward the finite element space
std::size_t getSize ()
get the size of the Finite Element Space
std::size_t get_max_bdr_attributes ()
get the maximum number of boundaries
int get_dimension ()
get the dimension of the problem
void apply_uniform_refinement (const int &level)
Apply nb_ref uniform refinement.
void make_periodic_mesh (std::vector< mfem::Vector >)
Create the periodic mesh using the vertex mapping defined by the translations vector.
~SpatialDiscretization ()
Destroy the Spatial Discretization< T>:: Spatial Discretization object.
Data Fields
int fe_order_
int dimension_
mfem::Mesh mesh_
int mesh_max_bdr_attributes_
Detailed Description
template<class T, int DIM>
class SpatialDiscretization< T, DIM >
Class for defining the spatial discretization with a mesh coming from a GMSH file or built by using dedicated MFEM methods.
Template Parameters
T
DIM
Definition at line 44 of file Spatial.hpp.
Constructor & Destructor Documentation
 SpatialDiscretization()
template<class T , int DIM>
SpatialDiscretization< T, DIM >::~SpatialDiscretization ()
Destroy the Spatial Discretization< T>:: Spatial Discretization object.
Template Parameters
T
Definition at line 504 of file Spatial.hpp.
{}
Member Function Documentation
apply_uniform_refinement()
template<class T , int DIM>
void SpatialDiscretization< T, DIM >::apply_uniform_refinement (const int & nb_ref)
Apply nb_ref uniform refinement.
Template Parameters
T
Parameters
nb_ref
Definition at line 477 of file Spatial.hpp.
                                                                              {
  for (auto l = 0; l < nb_ref; l++) {
    this->mesh_.UniformRefinement();
  }
}
get_dimension()
template<class T , int DIM>
int SpatialDiscretization< T, DIM >::get_dimension ()
get the dimension of the problem
Template Parameters
T
Returns
int
Definition at line 466 of file Spatial.hpp.
Referenced by Variable< T, DIM >::Variable().
                                                 {
  return this->dimension_;
}
get_finite_element_space()
template<class T , int DIM>
mfem::FiniteElementSpace * SpatialDiscretization< T, DIM >::get_finite_element_space ()
return a pointer toward the finite element space
Template Parameters
T
Returns
mfem::FiniteElementSpace*
Definition at line 433 of file Spatial.hpp.
Referenced by BoundaryConditions< T, DIM >::BoundaryConditions(), PhaseFieldOperatorBase< T, DIM, NLFI >::PhaseFieldOperatorBase(), and Variable< T, DIM >::Variable().
                                                                                {
  return this->fespace_;
}
get_max_bdr_attributes()
template<class T , int DIM>
std::size_t SpatialDiscretization< T, DIM >::get_max_bdr_attributes ()
get the maximum number of boundaries
Template Parameters
T
Returns
int
Definition at line 455 of file Spatial.hpp.
Referenced by BoundaryConditions< T, DIM >::BoundaryConditions().
                                                                {
  return this->mesh_max_bdr_attributes_;
}
get_mesh()
template<class T , int DIM>
mfem::Mesh & SpatialDiscretization< T, DIM >::get_mesh ()
return a pointer of Mesh
Template Parameters
T
Returns
mfem::Mesh&
Definition at line 409 of file Spatial.hpp.
                                                  {
  return this->mesh_;
}
getSize()
template<class T , int DIM>
std::size_t SpatialDiscretization< T, DIM >::getSize ()
get the size of the Finite Element Space
Template Parameters
T
Returns
int
Definition at line 444 of file Spatial.hpp.
                                                 {
  return this->size_;
}
make_periodic_mesh()
template<class T , int DIM>
void SpatialDiscretization< T, DIM >::make_periodic_mesh (std::vector< mfem::Vector > translations)
Create the periodic mesh using the vertex mapping defined by the translations vector.
Template Parameters
T
DIM
Parameters
translations
Definition at line 491 of file Spatial.hpp.
Referenced by specialized_spatial_constructor< T, 2 >::operator()().
                                                                                         {
  const auto tol = 1.e-6;
  std::vector<int> periodicMap = this->mesh_.CreatePeriodicVertexMapping(translations, tol);
  auto periodic_mesh = mfem::Mesh::MakePeriodic(this->mesh_, periodicMap);
  this->mesh_ = mfem::Mesh(periodic_mesh, true); // replace the input mesh with the periodic one
}
set_finite_element_space()
template<class T , int DIM>
void SpatialDiscretization< T, DIM >::set_finite_element_space ()
Set the FE_Collection, the FE_Space and associated size.
Template Parameters
T
Returns
mfem::FiniteElementSpace*
Definition at line 420 of file Spatial.hpp.
Referenced by specialized_spatial_constructor< T, 1 >::operator()(), specialized_spatial_constructor< T, 2 >::operator()(), and specialized_spatial_constructor< T, 3 >::operator()().
                                                             {
  this->fecollection_ = new T(this->fe_order_, this->dimension_);
  this->fespace_ = new mfem::FiniteElementSpace(&this->mesh_, this->fecollection_);
  this->size_ = this->fespace_->GetTrueVSize();
}
The documentation for this class was generated from the following file:
Spatial.hpp