UtilsForSolvers Class Reference
Useful methods for managing solvers.
#include </home/ci230846/home-local/MyGitProjects/COMPONENT/PF-MFEM/Utils/UtilsForSolvers.hpp>
Public Member Functions
void BuildSolver (mfem::IterativeSolver &solver, mfem::Solver &solv_method, mfem::Operator &ope)
Build solver depending on given preconditionner and operator.
void SetSolverParameters (mfem::IterativeSolver &solver, const int &_print_level, const bool _iterative_mode, const int &_n_iter_max, const double &_n_rel_tol, const double &_n_abs_tol)
Set all parameters used by the solver.
Detailed Description
Useful methods for managing solvers.
Definition at line 17 of file UtilsForSolvers.hpp.
Member Function Documentation
BuildSolver()
void UtilsForSolvers::BuildSolver (mfem::IterativeSolver & solver, mfem::Solver & preconditionner, mfem::Operator & ope)
Build solver depending on given preconditionner and operator.
Parameters
solver IterativeSolver
preconditionner Preconditionner
ope Operator
Definition at line 32 of file UtilsForSolvers.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::SetConstantParameters(), and PhaseFieldOperatorBase< T, DIM, NLFI >::SetTransientParameters().
                                                     {
  solver.SetPreconditioner(preconditionner);
  solver.SetOperator(ope);
}
SetSolverParameters()
void UtilsForSolvers::SetSolverParameters (mfem::IterativeSolver & solver, const int & _print_level, const bool _iterative_mode, const int & _n_iter_max, const double & _n_rel_tol, const double & _n_abs_tol)
Set all parameters used by the solver.
Parameters
solver IterativeSolver
_print_level printing level
_iterative_mode flag to activate the iterative mode (initialization of the Iterative Solver, False by default)
_n_iter_max maximum number of iterations used by the IterativeSolver
_n_rel_tol relative tolerance used by the IterativeSolver convergence test
_n_abs_tol absolute tolerance used by the IterativeSolver convergence test
Definition at line 48 of file UtilsForSolvers.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::SetConstantParameters(), and PhaseFieldOperatorBase< T, DIM, NLFI >::SetTransientParameters().
                                                                                              {
  solver.SetPrintLevel(_print_level);
  solver.iterative_mode = _iterative_mode;
  solver.SetMaxIter(_n_iter_max);
  solver.SetRelTol(_n_rel_tol);
  solver.SetAbsTol(_n_abs_tol);
}
The documentation for this class was generated from the following file:
UtilsForSolvers.hpp