Parameters Class Reference
Class used to manage a list of Parameter.
#include </home/ci230846/home-local/MyGitProjects/COMPONENT/PF-MFEM/Parameters/Parameters.hpp>
Public Member Functions
Parameters ()
Construct a new Parameters:: Parameters object.
template<class... Args>
Parameters (const Args &... args)
Construct a new Parameters:: Parameters object.
void add (const Parameter &param)
add a new parameters
void ListParamByName ()
double get_parameter_value (const std::string &name) const
get double value of a parameter by name
bool get_option_value (const std::string &name) const
get boolean option of a parameter by name
std::map< std::string, double > getMapParameters () const
transform list of parameters into a map<string,double>
~Parameters ()
Destroy the Parameters:: Parameters object.
Detailed Description
Class used to manage a list of Parameter.
Definition at line 23 of file Parameters.hpp.
Constructor & Destructor Documentation
Parameters()
template<class... Args>
Parameters::Parameters (const Args &... args) [explicit]
Construct a new Parameters:: Parameters object.
Template Parameters
Args
Parameters
args
Definition at line 53 of file Parameters.hpp.
                                          {
  this->vect_params_ = std::vector<Parameter>{args...};
}
Member Function Documentation
add()
void Parameters::add (const Parameter & param)
add a new parameters
Parameters
param parameter to add
Definition at line 62 of file Parameters.hpp.
{ this->vect_params_.emplace_back(param); }
get_option_value()
bool Parameters::get_option_value (const std::string & name) const
get boolean option of a parameter by name
Parameters
name
Returns
true
false
Definition at line 94 of file Parameters.hpp.
Referenced by TimeDiscretization< T, DC, DIM >::TimeDiscretization().
                                                             {
  bool active_option = false;
  for (const auto& p : this->vect_params_) {
    auto pn = p.getName();
    if (pn == name) {
      active_option = std::get<bool>(p.getValue());
    }
  }
  return active_option;
}
get_parameter_value()
double Parameters::get_parameter_value (const std::string & name) const
get double value of a parameter by name
Parameters
name name of the parameter
Returns
double double value of the parameter
Definition at line 70 of file Parameters.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::PhaseFieldOperatorBase(), and TimeDiscretization< T, DC, DIM >::TimeDiscretization().
                                                                  {
  const auto lowest_float = std::numeric_limits<float>::lowest();
  auto value = std::numeric_limits<double>::lowest();
  for (const auto& p : this->vect_params_) {
    auto pn = p.getName();
    if (pn == name) {
      value = std::get<double>(p.getValue());
    }
  }
  if (value > lowest_float) {
    return value;
  } else {
    throw std::runtime_error("Parameter " + name + " not found");
  }
}
getMapParameters()
std::map< std::string, double > Parameters::getMapParameters () const
transform list of parameters into a map<string,double>
Returns
std::map<std::string, double>
Definition at line 112 of file Parameters.hpp.
                                                             {
  std::map<std::string, double> map_par;
  for (auto p : this->vect_params_) {
    auto name = p.getName();
    auto value = std::get<double>(p.getValue());
    map_par.try_emplace(name, value);
  }
  return map_par;
}
The documentation for this class was generated from the following file:
Parameters.hpp