Variable< T, DIM > Class Template Reference
Public Member Functions
template<class... Args>
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const std::string &initial_condition_name, std::tuple< Args... > args1)
Construct a new Variable:: Variable object.
template<class... Args1, class... Args2>
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const std::string &initial_condition_name, std::tuple< Args1... > args1, const std::string &analytical_solution_name, std::tuple< Args2... > args2)
Construct a new Variable:: Variable object.
template<class... Args>
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const std::string &initial_condition_name, std::tuple< Args... > args1, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const mfem::FunctionCoefficient &initial_condition_function)
Construct a new Variable<T>:: Variable object.
template<class... Args>
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const mfem::FunctionCoefficient &initial_condition_function, const std::string &analytical_solution_name, std::tuple< Args... > args1)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const mfem::FunctionCoefficient &initial_condition_function, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const double &initial_condition_value)
Construct a new Variable<T>:: Variable object.
template<class... Args>
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const double &initial_condition_value, const std::string &analytical_solution_name, std::tuple< Args... > args1)
Construct a new Variable<T>:: Variable object.
Variable (SpatialDiscretization< T, DIM > *spatial, const BoundaryConditions< T, DIM > &bcs, const std::string &variable_name, const std::string &type, const double &initial_condition_value, const mfem::FunctionCoefficient &analytical_solution_function)
Construct a new Variable<T>:: Variable object.
std::string getVariableName () const
Get the name of the Variable.
VariableType::value getVariableType ()
Get the Type of the Variable.
void update (const mfem::Vector &unk)
update the GridFunction on the basis of its associated unknown vector
mfem::Vector get_unknown ()
return the unkown vector
mfem::GridFunction get_gf () const
return the gridfunction associated to the unknown
mfem::GridFunction get_igf () const
std::shared_ptr< std::function< double(const mfem::Vector &, double)> > get_analytical_solution ()
return the gridfunction associated to the analytical solution
BoundaryConditions< T, DIM > * get_boundary_conditions ()
return the boundary condition object associated to the variable
~Variable ()
Destroy the Variable:: Variable object.
Detailed Description
template<class T, int DIM>
class Variable< T, DIM >
Definition at line 24 of file Variable.hpp.
Constructor & Destructor Documentation
Variable() [1/9]
template<class T , int DIM>
template<class... Args>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const std::string & initial_condition_name, std::tuple< Args... > args1)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_name
Definition at line 124 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  const auto dim = spatial->get_dimension();
  std::apply(
      [dim, initial_condition_name, this](Args... args) {
        Variable<T, DIM>::setInitialCondition(dim, initial_condition_name, args...);
      },
      args1);
  // mfem::ConstantCoefficient cc(0.);
  // this->uh_.ProjectCoefficient(cc);
  // this->uh_.GetTrueDofs(this->unk_);
}
Variable() [2/9]
template<class T , int DIM>
template<class... Args1, class... Args2>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const std::string & initial_condition_name, std::tuple< Args1... > args1, const std::string & analytical_solution_name, std::tuple< Args2... > args2)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_name
analytical_solution_name
Definition at line 156 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  const auto dim = spatial->get_dimension();
  std::apply(
      [dim, initial_condition_name, this](Args1... args) {
        this->setInitialCondition(dim, initial_condition_name, args...);
      },
      args1);
  std::apply(
      [dim, analytical_solution_name, this](Args2... args) {
        this->setAnalyticalSolution(dim, analytical_solution_name, args...);
      },
      args2);
}
Variable() [3/9]
template<class T , int DIM>
template<class... Args>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const std::string & initial_condition_name, std::tuple< Args... > args1, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_name
analytical_solution_function
Definition at line 190 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  const auto dim = spatial->get_dimension();
  std::apply([dim, initial_condition_name, this](
                 Args... args) { this->setInitialCondition(dim, initial_condition_name, args...); },
             args1);
  this->setAnalyticalSolution(analytical_solution_function);
}
Variable() [4/9]
template<class T , int DIM>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const mfem::FunctionCoefficient & initial_condition_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_function
Definition at line 217 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  this->setInitialCondition(initial_condition_function);
}
Variable() [5/9]
template<class T , int DIM>
template<class... Args>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const mfem::FunctionCoefficient & initial_condition_function, const std::string & analytical_solution_name, std::tuple< Args... > args1)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_function
analytical_solution_name
Definition at line 240 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  const auto dim = spatial->get_dimension();
  this->setInitialCondition(initial_condition_function);
  std::apply(
      [dim, analytical_solution_name, this](Args... args) {
        this->setAnalyticalSolution(dim, analytical_solution_name, args...);
      },
      args1);
}
Variable() [6/9]
template<class T , int DIM>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const mfem::FunctionCoefficient & initial_condition_function, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_function
analytical_solution_function
Definition at line 269 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  this->setInitialCondition(initial_condition_function);
  this->setAnalyticalSolution(analytical_solution_function);
}
Variable() [7/9]
template<class T , int DIM>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const double & initial_condition_value)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_value
Definition at line 292 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  this->setInitialCondition(initial_condition_value);
}
Variable() [8/9]
template<class T , int DIM>
template<class... Args>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const double & initial_condition_value, const std::string & analytical_solution_name, std::tuple< Args... > args1)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_value
analytical_solution_name
Definition at line 312 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_dimension(), and SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  const auto dim = spatial->get_dimension();
  this->setInitialCondition(initial_condition_value);
  std::apply(
      [dim, analytical_solution_name, this](Args... args) {
        this->setAnalyticalSolution(dim, analytical_solution_name, args...);
      },
      args1);
}
Variable() [9/9]
template<class T , int DIM>
Variable< T, DIM >::Variable (SpatialDiscretization< T, DIM > * spatial, const BoundaryConditions< T, DIM > & bcs, const std::string & variable_name, const std::string & type, const double & initial_condition_value, const mfem::FunctionCoefficient & analytical_solution_function)
Construct a new Variable<T>:: Variable object.
Parameters
fespace
variable_name
type
initial_condition_value
analytical_solution_function
Definition at line 340 of file Variable.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space().
    : bcs_(bcs), variable_name_(variable_name) {
  this->fespace_ = spatial->get_finite_element_space();
  this->setVariableType(type);
  this->uh_.SetSpace(fespace_);
  this->setInitialCondition(initial_condition_value);
  this->setAnalyticalSolution(analytical_solution_function);
}
Member Function Documentation
get_analytical_solution()
template<class T , int DIM>
std::shared_ptr< std::function< double(const mfem::Vector &, double)> > Variable< T, DIM >::get_analytical_solution ()
return the gridfunction associated to the analytical solution
Returns
mfem::GridFunction return the function associated to the analytical solution
Template Parameters
T
DIM
Returns
std::function<double(const mfem::Vector&, double)>
Definition at line 488 of file Variable.hpp.
                                          {
  return this->analytical_solution_;
}
get_boundary_conditions()
template<class T , int DIM>
BoundaryConditions< T, DIM > * Variable< T, DIM >::get_boundary_conditions ()
return the boundary condition object associated to the variable
Template Parameters
T
DIM
Returns
BoundaryConditions<T, DIM>
Definition at line 500 of file Variable.hpp.
                                                                      {
  return &this->bcs_;
}
get_gf()
template<class T , int DIM>
mfem::GridFunction Variable< T, DIM >::get_gf () const
return the gridfunction associated to the unknown
Returns
mfem::GridFunction
Definition at line 465 of file Variable.hpp.
                                                {
  return this->uh_;
}
get_unknown()
template<class T , int DIM>
mfem::Vector Variable< T, DIM >::get_unknown ()
return the unkown vector
Returns
mfem::Vector
Definition at line 455 of file Variable.hpp.
                                         {
  return this->unk_;
}
getVariableName()
template<class T , int DIM>
std::string Variable< T, DIM >::getVariableName () const
Get the name of the Variable.
Returns
std::string name of the variable
Definition at line 510 of file Variable.hpp.
                                                  {
  return this->variable_name_;
}
getVariableType()
template<class T , int DIM>
VariableType::value Variable< T, DIM >::getVariableType ()
Get the Type of the Variable.
Returns
VariableType::value type of the variable
Definition at line 520 of file Variable.hpp.
                                                    {
  return this->variable_type_;
}
The documentation for this class was generated from the following file:
Variable.hpp