BoundaryConditions< T, DIM > Class Template Reference
Class used to manage boundary conditions.
#include </home/ci230846/home-local/MyGitProjects/COMPONENT/PF-MFEM/BCs/BoundaryConditions.hpp>
Public Member Functions
template<class... Args>
BoundaryConditions (SpatialDiscretization< T, DIM > *spatial, const Args &...boundaries)
Construct a new Boundary Conditions:: Boundary Conditions object.
void SetBoundaryConditions (mfem::Vector &u)
Set boundary conditions.
mfem::Array< int > GetEssentialDofs ()
return the list of essential dofs
~BoundaryConditions ()
Destroy the Boundary Conditions:: Boundary Conditions object.
Detailed Description
template<class T, int DIM>
class BoundaryConditions< T, DIM >
Class used to manage boundary conditions.
Definition at line 25 of file BoundaryConditions.hpp.
Constructor & Destructor Documentation
BoundaryConditions()
template<class T , int DIM>
template<class... Args>
BoundaryConditions< T, DIM >::BoundaryConditions (SpatialDiscretization< T, DIM > * spatial, const Args &... boundaries)
Construct a new Boundary Conditions:: Boundary Conditions object.
Template Parameters
Args
Parameters
fespace
mesh_max_bdr_attributes
boundaries
Definition at line 52 of file BoundaryConditions.hpp.
References SpatialDiscretization< T, DIM >::get_finite_element_space(), and SpatialDiscretization< T, DIM >::get_max_bdr_attributes().
                                                                          {
  this->fespace_ = spatial->get_finite_element_space();
  const auto &mesh_max_bdr_attributes = spatial->get_max_bdr_attributes();
  auto bdrs = std::vector<Boundary>{boundaries...};
  Dirichlet_bdr_.SetSize(mesh_max_bdr_attributes);
  Dirichlet_value_.SetSize(mesh_max_bdr_attributes);
  bool exist_periodic_bdr = {false};
  [bdrs, &exist_periodic_bdr]() {
    bool is_periodic = false;
    for (const auto &bdr : bdrs) {
      if (bdr.is_essential_boundary()) {
        is_periodic = true;
        break;
      }
    }
    return is_periodic;
  };
  bool test_periodic_bdr = (mesh_max_bdr_attributes != bdrs.size()) && exist_periodic_bdr;
  bool test_standard_bdr = mesh_max_bdr_attributes == bdrs.size();
  if (test_periodic_bdr || test_standard_bdr) {
    for (const auto &bdr : bdrs) {
      const auto &id = bdr.get_boundary_index();
      if (bdr.is_essential_boundary()) {
        Dirichlet_bdr_[id] = 1;
      } else {
        Dirichlet_bdr_[id] = 0;
      }
      Dirichlet_value_[id] = bdr.get_boundary_value();
    }
    this->fespace_->GetEssentialTrueDofs(this->Dirichlet_bdr_, this->ess_tdof_list_);
  } else {
    throw std::runtime_error(
        "BoundaryConditions::BoundaryConditions(): user-defined boundaries " +
        std::to_string(bdrs.size()) +
        " are unconsistent with the total number of boundaries associated to the mesh " +
        std::to_string(mesh_max_bdr_attributes));
  }
}
Member Function Documentation
GetEssentialDofs()
template<class T , int DIM>
mfem::Array< int > BoundaryConditions< T, DIM >::GetEssentialDofs ()
return the list of essential dofs
Returns
mfem::Array<int> array of essential dofs
Definition at line 100 of file BoundaryConditions.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::initialize().
                                                            {
  return this->ess_tdof_list_;
}
SetBoundaryConditions()
template<class T , int DIM>
void BoundaryConditions< T, DIM >::SetBoundaryConditions (mfem::Vector & u)
Set boundary conditions.
Parameters
u unknown vector
Definition at line 110 of file BoundaryConditions.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::ImplicitSolve(), and PhaseFieldOperatorBase< T, DIM, NLFI >::initialize().
                                                                    {
  mfem::Array<int> tmp_array_bdr(this->Dirichlet_bdr_.Size());
  for (auto i = 0; i < this->Dirichlet_bdr_.Size(); i++) {
    tmp_array_bdr = 0;
    mfem::Array<int> dof;
    if (this->Dirichlet_bdr_[i] > 0) {
      tmp_array_bdr[i] = 1;
      this->fespace_->GetEssentialTrueDofs(tmp_array_bdr, dof);
      u.SetSubVector(dof, this->Dirichlet_value_[i]);
    }
  }
} // end of SetBoundaryConditions
The documentation for this class was generated from the following file:
BoundaryConditions.hpp