PhaseFieldOperatorMelting< T, DIM, NLFI > Class Template Reference
PhaseFieldOperatorMelting class.
#include </home/ci230846/home-local/MyGitProjects/COMPONENT/PF-MFEM/Operators/PhaseFieldOperatorMelting.hpp>
Public Member Functions
PhaseFieldOperatorMelting (SpatialDiscretization< T, DIM > *spatial, const Parameters &params, Variables< T, DIM > &vars)
Construct a new Phase Field Operator:: Phase Field Operator object.
NLFI * set_nlfi_ptr (const double dt, const mfem::Vector &u) override
Set the NonLinearFormIntegrator dedicated to melting coupling.
virtual ~PhaseFieldOperatorMelting ()
Destroy the Phase Field Operator Melting< T, DIM, NLFI>:: Phase Field Operator Melting object.
virtual void Mult (const mfem::Vector &u, mfem::Vector &du_dt) const
Compute the right-hand side of the ODE system.
virtual void ImplicitSolve (const double dt, const mfem::Vector &u, mfem::Vector &k)
Solve the Backward-Euler equation: k = f(phi + dt*k, t), for the unknown k.
void SetConstantParameters (const double dt, mfem::Vector &u)
Set current dt, unk values - needed to compute action and Jacobian.
void SetTransientParameters (const double dt, const mfem::Vector &u)
Set current dt, unk values - needed to compute action and Jacobian. solution_coef.
void initialize (const double &initial_time)
Initialization stage.
void ComputeEnergies (const std::tuple< int, double, double > &iter, const mfem::Vector &u)
Compute Phase-field Energies.
void ComputeError (const std::tuple< int, double, double > &iter, const mfem::Vector &u, std::function< double(const mfem::Vector &, double)> solution_func)
Compute L2 error.
void get_source_term (mfem::Vector &source_term) const
get the source term
const std::map< std::tuple< int, double, double >, double > get_l2_error () const
Get a value of a map of L2 errors at a given iteration.
const std::map< std::tuple< int, double, double >, double > get_energy_density () const
Get a of a map of interfacial energy at a given iteration.
const std::map< std::tuple< int, double, double >, double > get_energy_interface () const
Get a of a map of interfacial energy at a given iteration.
Protected Attributes
mfem::FiniteElementSpace * fespace_
mfem::Array< int > ess_tdof_list_
mfem::BilinearForm * M
mfem::CGSolver M_solver
mfem::DSmoother M_prec
mfem::SparseMatrix Mmat
mfem::LinearForm * RHS
mfem::NonlinearForm * N
mfem::Solver * J_solver
mfem::Solver * J_prec
BoundaryConditions< T, DIM > * bcs_
Variables< T, DIM > vars_
mfem::NewtonSolver newton_solver_
PhaseFieldReducedOperator * reduced_oper
double mobility_coeff_
double omega_
double lambda_
std::function< double(const mfem::Vector &, double)> src_func_
double current_dt_
mfem::Vector z
std::string source_term_name_
Detailed Description
template<class T, int DIM, class NLFI>
class PhaseFieldOperatorMelting< T, DIM, NLFI >
PhaseFieldOperatorMelting class.
Definition at line 46 of file PhaseFieldOperatorMelting.hpp.
Constructor & Destructor Documentation
PhaseFieldOperatorMelting()
template<class T , int DIM, class NLFI >
PhaseFieldOperatorMelting< T, DIM, NLFI >::PhaseFieldOperatorMelting (SpatialDiscretization< T, DIM > * spatial, const Parameters & params, Variables< T, DIM > & vars)
Construct a new Phase Field Operator:: Phase Field Operator object.
Parameters
fespace Finite Element space
params list of Parameters
u unknown vector
Definition at line 68 of file PhaseFieldOperatorMelting.hpp.
    : PhaseFieldOperatorBase<T, DIM, NLFI>(spatial, params, vars) {}
 PhaseFieldOperatorMelting()
template<class T , int DIM, class NLFI >
PhaseFieldOperatorMelting< T, DIM, NLFI >::~PhaseFieldOperatorMelting () [virtual]
Destroy the Phase Field Operator Melting< T, DIM, NLFI>:: Phase Field Operator Melting object.
Template Parameters
T
DIM
Definition at line 103 of file PhaseFieldOperatorMelting.hpp.
{}
Member Function Documentation
ComputeEnergies()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::ComputeEnergies (const std::tuple< int, double, double > & iter, const mfem::Vector & u) [inherited]
Compute Phase-field Energies.
Parameters
u unknown vector
Returns
const double
Definition at line 338 of file PhaseFieldOperatorBase.hpp.
                                                                    {
  mfem::GridFunction un_gf(this->fespace_);
  un_gf.SetFromTrueDofs(u);
  mfem::GridFunction gf(this->fespace_);
  EnergyCoefficient g(&un_gf, 0.5 * this->lambda_, this->omega_);
  gf.ProjectCoefficient(g);
  mfem::GridFunction sigf(this->fespace_);
  EnergyCoefficient sig(&un_gf, this->lambda_, 0.);
  sigf.ProjectCoefficient(sig);
  // Calcul de l'intégrale de l'objet FunctionCoefficient sur le domaine
  mfem::ConstantCoefficient zero(0.);
  const auto energy = gf.ComputeL1Error(zero);
  this->energy_density_.try_emplace(iter, energy);
  const auto interfacial_energy = sigf.ComputeL1Error(zero);
  this->energy_interface_.try_emplace(iter, interfacial_energy);
}
ComputeError()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::ComputeError (const std::tuple< int, double, double > & iter, const mfem::Vector & u, std::function< double(const mfem::Vector &, double)> solution_func) [inherited]
Compute L2 error.
Parameters
u unknown vector
Returns
const double
Definition at line 364 of file PhaseFieldOperatorBase.hpp.
                                                                   {
  mfem::GridFunction gf(this->fespace_);
  gf.SetFromTrueDofs(u);
  mfem::FunctionCoefficient solution_coef(solution_func);
  solution_coef.SetTime(this->GetTime());
  const auto error = gf.ComputeL2Error(solution_coef);
  this->error_l2_.try_emplace(iter, error);
}
get_energy_density()
template<class T , int DIM, class NLFI >
const std::map< std::tuple< int, double, double >, double > PhaseFieldOperatorBase< T, DIM, NLFI >::get_energy_density () const [inherited]
Get a of a map of interfacial energy at a given iteration.
Template Parameters
T
DIM
NLFI
Returns
const std::map<std::tuple<int, double, double>, double>
Definition at line 417 of file PhaseFieldOperatorBase.hpp.
                                                               {
  return this->energy_density_;
}
get_energy_interface()
template<class T , int DIM, class NLFI >
const std::map< std::tuple< int, double, double >, double > PhaseFieldOperatorBase< T, DIM, NLFI >::get_energy_interface () const [inherited]
Get a of a map of interfacial energy at a given iteration.
Template Parameters
T
DIM
NLFI
Returns
const std::map<std::tuple<int, double, double>, double>
Definition at line 431 of file PhaseFieldOperatorBase.hpp.
                                                                 {
  return this->energy_interface_;
}
get_l2_error()
template<class T , int DIM, class NLFI >
const std::map< std::tuple< int, double, double >, double > PhaseFieldOperatorBase< T, DIM, NLFI >::get_l2_error () const [inherited]
Get a value of a map of L2 errors at a given iteration.
Template Parameters
T
DIM
NLFI
Parameters
iter
Returns
const std::map<std::tuple<int, double, double>, double>
Definition at line 403 of file PhaseFieldOperatorBase.hpp.
                                                         {
  return this->error_l2_;
}
get_source_term()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::get_source_term (mfem::Vector & source_term) const [inherited]
get the source term
Template Parameters
T
DIM
NLFI
Definition at line 383 of file PhaseFieldOperatorBase.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::ImplicitSolve(), and PhaseFieldOperatorBase< T, DIM, NLFI >::Mult().
                                                                                        {
  std::shared_ptr<mfem::LinearForm> RHSS(new mfem::LinearForm(this->fespace_));
  mfem::FunctionCoefficient src(this->src_func_);
  src.SetTime(this->GetTime());
  RHSS->AddDomainIntegrator(new mfem::DomainLFIntegrator(src));
  RHSS->Assemble();
  source_term = *RHSS.get();
}
ImplicitSolve()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::ImplicitSolve (const double dt, const mfem::Vector & u, mfem::Vector & du_dt) [virtual], [inherited]
Solve the Backward-Euler equation: k = f(phi + dt*k, t), for the unknown k.
Solve the Backward-Euler equation: k = f(u + dt*k, t), for the unknown k. This is the only requirement for high-order SDIRK implicit integration.
Parameters
dt current time step
u unknown vector
du_dt unkwon time derivative vector
Definition at line 302 of file PhaseFieldOperatorBase.hpp.
References PhaseFieldOperatorBase< T, DIM, NLFI >::get_source_term(), BoundaryConditions< T, DIM >::SetBoundaryConditions(), PhaseFieldReducedOperator::SetParameters(), and PhaseFieldOperatorBase< T, DIM, NLFI >::SetTransientParameters().
                                                                            {
  const auto sc = height;
  mfem::Vector v(u.GetData(), sc);
  mfem::Vector dv_dt(du_dt.GetData(), sc);
  // // Solve the equation:
  // // du_dt = M^{-1}*[-K(u + dt*du_dt)]
  // // for du_dt
  this->bcs_->SetBoundaryConditions(v);
  this->SetTransientParameters(dt, v);
  reduced_oper->SetParameters(dt, &v);
  // Source term
  mfem::Vector source_term;
  if (!this->source_term_name_.empty()) {
    this->get_source_term(source_term);
  }
  dv_dt = v;
  dv_dt *= (1. / dt);
  this->newton_solver_.Mult(source_term, dv_dt);
  dv_dt.SetSubVector(this->ess_tdof_list_, 0.0); // pour Dirichlet ... uniquement?
  // std::cout << " PhaseFieldOperatorBase this->newton_solver_->Mult " << std::endl;
  MFEM_VERIFY(this->newton_solver_.GetConverged(), "Nonlinear solver did not converge.");
}
initialize()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::initialize (const double & initial_time) [inherited]
Initialization stage.
Parameters
vv
Definition at line 186 of file PhaseFieldOperatorBase.hpp.
References Variables< T, DIM >::get_variable(), BoundaryConditions< T, DIM >::GetEssentialDofs(), BoundaryConditions< T, DIM >::SetBoundaryConditions(), PhaseFieldOperatorBase< T, DIM, NLFI >::SetConstantParameters(), and PhaseFieldOperatorBase< T, DIM, NLFI >::SetTransientParameters().
                                                                                {
  this->SetTime(initial_time);
  auto &vv = vars_.get_variable("phi");
  auto u = vv.get_unknown();
  this->bcs_ = vv.get_boundary_conditions();
  this->ess_tdof_list_ = this->bcs_->GetEssentialDofs();
  this->bcs_->SetBoundaryConditions(u);
  this->SetConstantParameters(this->current_dt_, u);
  this->SetTransientParameters(this->current_dt_, u);
  vv.update(u);
}
Mult()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::Mult (const mfem::Vector & u, mfem::Vector & du_dt) const [virtual], [inherited]
Compute the right-hand side of the ODE system.
Parameters
u unknown vector
du_dt unkwon time derivative vector
Definition at line 276 of file PhaseFieldOperatorBase.hpp.
References PhaseFieldOperatorBase< T, DIM, NLFI >::get_source_term().
                                                                                            {
  const auto sc = height;
  mfem::Vector v(u.GetData(), sc);
  mfem::Vector dv_dt(du_dt.GetData(), sc);
  N->Mult(v, z);
  // Source term
  if (!this->source_term_name_.empty()) {
    mfem::Vector source_term;
    this->get_source_term(source_term);
    z -= source_term;
  }
  z.Neg(); // z = -z
  M_solver.Mult(z, dv_dt);
}
set_nlfi_ptr()
template<class T , int DIM, class NLFI >
NLFI * PhaseFieldOperatorMelting< T, DIM, NLFI >::set_nlfi_ptr (const double dt, const mfem::Vector & u) [override], [virtual]
Set the NonLinearFormIntegrator dedicated to melting coupling.
Template Parameters
T
DIM
Parameters
dt
u
Returns
NLFI*
Implements PhaseFieldOperatorBase< T, DIM, NLFI >.
Definition at line 82 of file PhaseFieldOperatorMelting.hpp.
                                                                                 {
  mfem::GridFunction un(this->fespace_);
  un.SetFromTrueDofs(u);
  // PhaseChange Coefficient
  PhaseChangeCoefficient phase_change;
  phase_change.SetTime(this->GetTime());
  un.ProjectCoefficient(phase_change);
  NLFI *nlfi_ptr = new NLFI(un, this->omega_, this->lambda_, this->mobility_coeff_, phase_change);
  return nlfi_ptr;
}
SetConstantParameters()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::SetConstantParameters (const double dt, mfem::Vector & u) [inherited]
Set current dt, unk values - needed to compute action and Jacobian.
Parameters
dt time-step
u unknown vector
ess_tdof_list array of dofs
Definition at line 250 of file PhaseFieldOperatorBase.hpp.
References UtilsForSolvers::BuildSolver(), and UtilsForSolvers::SetSolverParameters().
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::initialize().
                                                                                               {
  delete M;
  // Mass matrix (constant)
  M = new mfem::BilinearForm(this->fespace_);
  M->AddDomainIntegrator(new mfem::MassIntegrator());
  M->Assemble(0);
  mfem::SparseMatrix tmp;
  M->FormSystemMatrix(this->ess_tdof_list_, Mmat);
  this->ut_solver_.SetSolverParameters(
      M_solver, MassDefaultConstant::print_level, MassDefaultConstant::iterative_mode,
      MassDefaultConstant::iter_max, MassDefaultConstant::rel_tol, MassDefaultConstant::abs_tol);
  this->ut_solver_.BuildSolver(M_solver, M_prec, Mmat);
}
SetTransientParameters()
template<class T , int DIM, class NLFI >
void PhaseFieldOperatorBase< T, DIM, NLFI >::SetTransientParameters (const double dt, const mfem::Vector & u) [inherited]
Set current dt, unk values - needed to compute action and Jacobian. solution_coef.
Parameters
dt time-step
u unknown vector
Definition at line 210 of file PhaseFieldOperatorBase.hpp.
References UtilsForSolvers::BuildSolver(), PhaseFieldOperatorBase< T, DIM, NLFI >::reduced_oper, and UtilsForSolvers::SetSolverParameters().
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::ImplicitSolve(), and PhaseFieldOperatorBase< T, DIM, NLFI >::initialize().
                                                                                       {
  delete N;
  delete reduced_oper;
  // PhaseField reduced operator N
  N = new mfem::NonlinearForm(this->fespace_);
  mfem::GridFunction un_gf(this->fespace_);
  un_gf.SetFromTrueDofs(u);
  mfem::GridFunction un(this->fespace_);
  un.SetFromTrueDofs(u);
  NLFI *nlfi_ptr = set_nlfi_ptr(dt, u);
  N->AddDomainIntegrator(nlfi_ptr);
  N->SetEssentialTrueDofs(this->ess_tdof_list_);
  reduced_oper = new PhaseFieldReducedOperator(M, N);
  // Newton Solver
  this->ut_solver_.SetSolverParameters(
      this->newton_solver_, NewtonDefaultConstant::print_level,
      NewtonDefaultConstant::iterative_mode, NewtonDefaultConstant::iter_max,
      NewtonDefaultConstant::rel_tol, NewtonDefaultConstant::abs_tol);
  // TODO(ci230846) : cette partie devra etre generalisee pour un solveur iteratif
  J_solver = new mfem::UMFPackSolver;
  this->ut_solver_.BuildSolver(this->newton_solver_, *J_solver, *
      reduced_oper);
}
Field Documentation
reduced_oper
template<class T, int DIM, class NLFI>
PhaseFieldReducedOperator* PhaseFieldOperatorBase< T, DIM, NLFI >::reduced_oper [protected], [inherited]
Nonlinear operator defining the reduced backward Euler equation for the velocity. Used in the implementation of method ImplicitSolve.
Definition at line 80 of file PhaseFieldOperatorBase.hpp.
Referenced by PhaseFieldOperatorBase< T, DIM, NLFI >::SetTransientParameters().
The documentation for this class was generated from the following file:
PhaseFieldOperatorMelting.hpp