specialized_spatial_constructor< T, 2 > Struct Template Reference
Specialization for dimension two.
#include </home/ci230846/home-local/MyGitProjects/COMPONENT/PF-MFEM/Spatial/Spatial.hpp>
Public Member Functions
template<typename... Args>
void operator() (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, const std::string &file)
operator() specialized for a mesh built from GMSH file
template<typename... Args>
void operator() (SpatialDiscretization< T, 2 > &a_my_class, const std::string &mesh_type, const int &fe_order, std::tuple< Args... > tup_args)
operator() specialized for a mesh built from MFEM methods
Detailed Description
template<typename T>
struct specialized_spatial_constructor< T, 2 >
Specialization for dimension two.
Template Parameters
T
Definition at line 188 of file Spatial.hpp.
Member Function Documentation
operator()() [1/2]
template<typename T >
template<typename... Args>
void specialized_spatial_constructor< T, 2 >::operator() (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, const std::string & file) [inline]
operator() specialized for a mesh built from GMSH file
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
file
Definition at line 199 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::set_finite_element_space().
                                                              {
    a_my_class.fe_order_ = fe_order;
    a_my_class.dimension_ = 2;
    switch (Meshes::from(mesh_type)) {
      case Meshes::GMSH: {
        if (std::filesystem::exists(file)) {
          const char *mesh_file = file.c_str();
          a_my_class.mesh_ = mfem::Mesh::LoadFromFile(mesh_file, 2, 1);
          break;
        } else {
          throw std::runtime_error("SpatialDiscretization::SpatialDiscretization: " + file +
                                   " doesn't exist. Please check your data.");
        }
      }
      default:
        throw std::runtime_error(
            "SpatialDiscretization::SpatialDiscretization: here, only GMSH mesh type is "
            "allowed");
        break;
    }
    std::cout << "CCI 0" << std::endl;
    a_my_class.mesh_max_bdr_attributes_ = a_my_class.mesh_.bdr_attributes.Max();
    std::cout << "CCI 1" << std::endl;
    a_my_class.mesh_.Save("FromGMSH");
    a_my_class.set_finite_element_space();
  }
operator()() [2/2]
template<typename T >
template<typename... Args>
void specialized_spatial_constructor< T, 2 >::operator() (SpatialDiscretization< T, 2 > & a_my_class, const std::string & mesh_type, const int & fe_order, std::tuple< Args... > tup_args) [inline]
operator() specialized for a mesh built from MFEM methods
Template Parameters
Args
Parameters
a_my_class
mesh_type
fe_order
tup_args
Definition at line 239 of file Spatial.hpp.
References SpatialDiscretization< T, DIM >::make_periodic_mesh(), and SpatialDiscretization< T, DIM >::set_finite_element_space().
                                                                   {
    a_my_class.fe_order_ = fe_order;
    auto tup_size = std::tuple_size<decltype(tup_args)>::value;
    a_my_class.dimension_ = 2;
    switch (Meshes::from(mesh_type)) {
      case Meshes::InlineSquareWithQuadrangles: {
        if (tup_size == 4) {
          const auto nx = std::get<0>(tup_args);
          const auto ny = std::get<1>(tup_args);
          const auto sx = std::get<2>(tup_args);
          const auto sy = std::get<3>(tup_args);
          a_my_class.mesh_ = mfem::Mesh::MakeCartesian2D(nx, ny, mfem::Element::QUADRILATERAL,
                                                         false, sx, sy, false);
          auto L = 2. * M_PI;
          // Create translation vectors defining the periodicity
          mfem::Vector x_translation({L, 0.0});
          mfem::Vector y_translation({0.0, L});
          std::vector<mfem::Vector> translations = {x_translation, y_translation};
          a_my_class.make_periodic_mesh(translations);
        } else {
          throw std::runtime_error(
              "SpatialDiscretization::SpatialDiscretization: InlineSquareWithQuadrangles "
              "requires "
              "four arguments, the number of nodes and the length along each direction");
        }
        break;
      }
      default:
        throw std::runtime_error(
            "SpatialDiscretization::SpatialDiscretization: here, only "
            "InlineLineWithSegments, "
            "InlineSquareWithTriangles, InlineSquareWithQuadrangles mesh types are allowed");
        break;
    }
    a_my_class.mesh_max_bdr_attributes_ = a_my_class.mesh_.bdr_attributes.Max();
    a_my_class.set_finite_element_space();
  }
The documentation for this struct was generated from the following file:
Spatial.hpp