var annotated_dup =
[
    [ "PhaseFieldPrivate", null, [
      [ "mmap", "structPhaseFieldPrivate_1_1mmap.html", "structPhaseFieldPrivate_1_1mmap" ]
    ] ],
    [ "AllenCahnMeltingNLFormIntegrator", "classAllenCahnMeltingNLFormIntegrator.html", "classAllenCahnMeltingNLFormIntegrator" ],
    [ "AllenCahnNLFormIntegrator", "classAllenCahnNLFormIntegrator.html", "classAllenCahnNLFormIntegrator" ],
    [ "AnalyticalFunctions", "classAnalyticalFunctions.html", "classAnalyticalFunctions" ],
    [ "AnalyticalFunctionsType", "structAnalyticalFunctionsType.html", "structAnalyticalFunctionsType" ],
    [ "Boundary", "classBoundary.html", "classBoundary" ],
    [ "BoundaryConditions", "classBoundaryConditions.html", "classBoundaryConditions" ],
    [ "BoundaryConditionType", "structBoundaryConditionType.html", "structBoundaryConditionType" ],
    [ "ConductionOperator", "classConductionOperator.html", "classConductionOperator" ],
    [ "DiffusionNLFIntegrator", "classDiffusionNLFIntegrator.html", "classDiffusionNLFIntegrator" ],
    [ "EnergyCoefficient", "classEnergyCoefficient.html", "classEnergyCoefficient" ],
    [ "InterfacialCoefficient", "classInterfacialCoefficient.html", "classInterfacialCoefficient" ],
    [ "MeltingCoefficient", "classMeltingCoefficient.html", "classMeltingCoefficient" ],
    [ "Meshes", "structMeshes.html", "structMeshes" ],
    [ "MobilityCoefficient", "classMobilityCoefficient.html", "classMobilityCoefficient" ],
    [ "MobilityFunctions", "classMobilityFunctions.html", "classMobilityFunctions" ],
    [ "multidimension_function", "structmultidimension__function.html", null ],
    [ "multidimension_function< 1 >", "structmultidimension__function_3_011_01_4.html", "structmultidimension__function_3_011_01_4" ],
    [ "multidimension_function< 2 >", "structmultidimension__function_3_012_01_4.html", "structmultidimension__function_3_012_01_4" ],
    [ "multidimension_function< 3 >", "structmultidimension__function_3_013_01_4.html", "structmultidimension__function_3_013_01_4" ],
    [ "NonlinearCoefficient", "classNonlinearCoefficient.html", "classNonlinearCoefficient" ],
    [ "Parameter", "classParameter.html", "classParameter" ],
    [ "Parameters", "classParameters.html", "classParameters" ],
    [ "PhaseChangeCoefficient", "classPhaseChangeCoefficient.html", "classPhaseChangeCoefficient" ],
    [ "PhaseFieldOperator", "classPhaseFieldOperator.html", "classPhaseFieldOperator" ],
    [ "PhaseFieldOperatorBase", "classPhaseFieldOperatorBase.html", "classPhaseFieldOperatorBase" ],
    [ "PhaseFieldOperatorMelting", "classPhaseFieldOperatorMelting.html", "classPhaseFieldOperatorMelting" ],
    [ "PhaseFieldReducedOperator", "classPhaseFieldReducedOperator.html", "classPhaseFieldReducedOperator" ],
    [ "PostProcessing", "classPostProcessing.html", "classPostProcessing" ],
    [ "potential_function", "structpotential__function.html", null ],
    [ "potential_function< 0, ThermodynamicsPotentialDiscretization::Explicit >", "structpotential__function_3_010_00_01ThermodynamicsPotentialDiscretization_1_1Explicit_01_4.html", "structpotential__function_3_010_00_01ThermodynamicsPotentialDiscretization_1_1Explicit_01_4" ],
    [ "potential_function< 0, ThermodynamicsPotentialDiscretization::Implicit >", "structpotential__function_3_010_00_01ThermodynamicsPotentialDiscretization_1_1Implicit_01_4.html", "structpotential__function_3_010_00_01ThermodynamicsPotentialDiscretization_1_1Implicit_01_4" ],
    [ "potential_function< 0, ThermodynamicsPotentialDiscretization::SemiImplicit >", "structpotential__function_3_010_00_01ThermodynamicsPotentialDiscretization_1_1SemiImplicit_01_4.html", "structpotential__function_3_010_00_01ThermodynamicsPotentialDiscretization_1_1SemiImplicit_01_4" ],
    [ "potential_function< 1, ThermodynamicsPotentialDiscretization::Explicit >", "structpotential__function_3_011_00_01ThermodynamicsPotentialDiscretization_1_1Explicit_01_4.html", "structpotential__function_3_011_00_01ThermodynamicsPotentialDiscretization_1_1Explicit_01_4" ],
    [ "potential_function< 1, ThermodynamicsPotentialDiscretization::Implicit >", "structpotential__function_3_011_00_01ThermodynamicsPotentialDiscretization_1_1Implicit_01_4.html", "structpotential__function_3_011_00_01ThermodynamicsPotentialDiscretization_1_1Implicit_01_4" ],
    [ "potential_function< 1, ThermodynamicsPotentialDiscretization::SemiImplicit >", "structpotential__function_3_011_00_01ThermodynamicsPotentialDiscretization_1_1SemiImplicit_01_4.html", "structpotential__function_3_011_00_01ThermodynamicsPotentialDiscretization_1_1SemiImplicit_01_4" ],
    [ "potential_function< 2, ThermodynamicsPotentialDiscretization::Explicit >", "structpotential__function_3_012_00_01ThermodynamicsPotentialDiscretization_1_1Explicit_01_4.html", "structpotential__function_3_012_00_01ThermodynamicsPotentialDiscretization_1_1Explicit_01_4" ],
    [ "potential_function< 2, ThermodynamicsPotentialDiscretization::Implicit >", "structpotential__function_3_012_00_01ThermodynamicsPotentialDiscretization_1_1Implicit_01_4.html", "structpotential__function_3_012_00_01ThermodynamicsPotentialDiscretization_1_1Implicit_01_4" ],
    [ "potential_function< 2, ThermodynamicsPotentialDiscretization::SemiImplicit >", "structpotential__function_3_012_00_01ThermodynamicsPotentialDiscretization_1_1SemiImplicit_01_4.html", "structpotential__function_3_012_00_01ThermodynamicsPotentialDiscretization_1_1SemiImplicit_01_4" ],
    [ "PotentialFunctions", "classPotentialFunctions.html", "classPotentialFunctions" ],
    [ "Problem", "classProblem.html", "classProblem" ],
    [ "Problems", "structProblems.html", "structProblems" ],
    [ "SourceTerm", "structSourceTerm.html", "structSourceTerm" ],
    [ "SourceTermCoefficient", "classSourceTermCoefficient.html", "classSourceTermCoefficient" ],
    [ "SpatialDiscretization", "classSpatialDiscretization.html", "classSpatialDiscretization" ],
    [ "specialized_spatial_constructor", "structspecialized__spatial__constructor.html", null ],
    [ "specialized_spatial_constructor< T, 1 >", "structspecialized__spatial__constructor_3_01T_00_011_01_4.html", "structspecialized__spatial__constructor_3_01T_00_011_01_4" ],
    [ "specialized_spatial_constructor< T, 2 >", "structspecialized__spatial__constructor_3_01T_00_012_01_4.html", "structspecialized__spatial__constructor_3_01T_00_012_01_4" ],
    [ "specialized_spatial_constructor< T, 3 >", "structspecialized__spatial__constructor_3_01T_00_013_01_4.html", "structspecialized__spatial__constructor_3_01T_00_013_01_4" ],
    [ "ThermodynamicRootFindingAlgorithm", "structThermodynamicRootFindingAlgorithm.html", "structThermodynamicRootFindingAlgorithm" ],
    [ "ThermodynamicsAllenCahnMobility", "structThermodynamicsAllenCahnMobility.html", "structThermodynamicsAllenCahnMobility" ],
    [ "ThermodynamicsFGR", "structThermodynamicsFGR.html", "structThermodynamicsFGR" ],
    [ "ThermodynamicsInitialization", "structThermodynamicsInitialization.html", "structThermodynamicsInitialization" ],
    [ "ThermodynamicsLinearPowerSourceTerm", "structThermodynamicsLinearPowerSourceTerm.html", "structThermodynamicsLinearPowerSourceTerm" ],
    [ "ThermodynamicsModel", "structThermodynamicsModel.html", "structThermodynamicsModel" ],
    [ "ThermodynamicsMolarVolumeType", "structThermodynamicsMolarVolumeType.html", "structThermodynamicsMolarVolumeType" ],
    [ "ThermodynamicsPotentials", "structThermodynamicsPotentials.html", "structThermodynamicsPotentials" ],
    [ "ThermodynamicsProperties", "structThermodynamicsProperties.html", "structThermodynamicsProperties" ],
    [ "ThermodynamicsStabilizationScheme", "structThermodynamicsStabilizationScheme.html", "structThermodynamicsStabilizationScheme" ],
    [ "ThermodynamicSubModels", "structThermodynamicSubModels.html", "structThermodynamicSubModels" ],
    [ "ThermodynamicsUnitForSettingConditions", "structThermodynamicsUnitForSettingConditions.html", "structThermodynamicsUnitForSettingConditions" ],
    [ "ThermodynamicsUpdateQuantitiesMethod", "structThermodynamicsUpdateQuantitiesMethod.html", "structThermodynamicsUpdateQuantitiesMethod" ],
    [ "ThermodynamicSystemsForMobilities", "structThermodynamicSystemsForMobilities.html", "structThermodynamicSystemsForMobilities" ],
    [ "TimeDiscretization", "classTimeDiscretization.html", "classTimeDiscretization" ],
    [ "TimeScheme", "structTimeScheme.html", "structTimeScheme" ],
    [ "UtilsForSolvers", "classUtilsForSolvers.html", "classUtilsForSolvers" ],
    [ "Variable", "classVariable.html", "classVariable" ],
    [ "Variables", "classVariables.html", "classVariables" ],
    [ "VariableType", "structVariableType.html", "structVariableType" ]
];