var files =
[
    [ "AllenCahnMeltingNLFormIntegrator.hpp", "AllenCahnMeltingNLFormIntegrator_8hpp_source.html", null ],
    [ "AllenCahnNLFormIntegrator.hpp", "AllenCahnNLFormIntegrator_8hpp_source.html", null ],
    [ "AllenCahnProblem.hpp", "AllenCahnProblem_8hpp_source.html", null ],
    [ "Coefficients/AnalyticalFunctions.hpp", "Coefficients_2AnalyticalFunctions_8hpp_source.html", null ],
    [ "Utils/AnalyticalFunctions.hpp", "Utils_2AnalyticalFunctions_8hpp_source.html", null ],
    [ "Boundary.hpp", "Boundary_8hpp_source.html", null ],
    [ "BoundaryConditions.hpp", "BoundaryConditions_8hpp_source.html", null ],
    [ "ConductionOperator.hpp", "ConductionOperator_8hpp_source.html", null ],
    [ "DiffusionNLFIntegrator.hpp", "DiffusionNLFIntegrator_8hpp_source.html", null ],
    [ "EnergyCoefficient.hpp", "EnergyCoefficient_8hpp_source.html", null ],
    [ "MobilityCoefficient.hpp", "MobilityCoefficient_8hpp_source.html", null ],
    [ "Parameter.hpp", "Parameter_8hpp_source.html", null ],
    [ "Parameters.hpp", "Parameters_8hpp_source.html", null ],
    [ "PhaseChangeCoefficient.hpp", "PhaseChangeCoefficient_8hpp_source.html", null ],
    [ "PhaseFieldConstants.hpp", "PhaseFieldConstants_8hpp_source.html", null ],
    [ "PhaseFieldMobilities.hpp", "PhaseFieldMobilities_8hpp_source.html", null ],
    [ "PhaseFieldOperator.hpp", "PhaseFieldOperator_8hpp_source.html", null ],
    [ "PhaseFieldOperatorBase.hpp", "PhaseFieldOperatorBase_8hpp_source.html", null ],
    [ "PhaseFieldOperatorMelting.hpp", "PhaseFieldOperatorMelting_8hpp_source.html", null ],
    [ "Coefficients/PhaseFieldOptions.hpp", "Coefficients_2PhaseFieldOptions_8hpp_source.html", null ],
    [ "Utils/PhaseFieldOptions.hpp", "Utils_2PhaseFieldOptions_8hpp_source.html", null ],
    [ "PhaseFieldPotentials.hpp", "PhaseFieldPotentials_8hpp_source.html", null ],
    [ "postprocessing.hpp", "postprocessing_8hpp_source.html", null ],
    [ "Problem.hpp", "Problem_8hpp_source.html", null ],
    [ "ReducedOperator.hpp", "ReducedOperator_8hpp_source.html", null ],
    [ "SourceTermCoefficient.hpp", "SourceTermCoefficient_8hpp_source.html", null ],
    [ "Spatial.hpp", "Spatial_8hpp_source.html", null ],
    [ "Time.hpp", "Time_8hpp_source.html", null ],
    [ "UtilsForSolvers.hpp", "UtilsForSolvers_8hpp_source.html", null ],
    [ "Variable.hpp", "Variable_8hpp_source.html", null ],
    [ "Variables.hpp", "Variables_8hpp_source.html", null ]
];