name: Build and Test SLOTH on Linux and MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    env: 
      CORES: $(nproc)
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-22.04, ubuntu-24.04]
        # gcc_version: [11, 14]
        # exclude:
        #   - os: ubuntu-22.04
        #     gcc_version: 14  
        #   - os: ubuntu-24.04
        #     gcc_version: 11 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: ${{github.workspace}}/spack       # Where to clone Spack
    - name: Install MFEM
      run: |
        spack install mfem+mpi+suite-sparse+sundials+superlu-dist@4.7.0 

    - name: Call Build SLOTH Workflow
      uses: ./.github/workflows/sloth-compile-and-test.yml
      with:
        cores: ${{ env.CORES }}
        workspace: ${{ github.workspace }}

  build-MacOS:
    runs-on: macos-latest
    env: 
      CORES: $(sysctl -n hw.ncpu)
    steps:
    - uses: actions/checkout@v4

    - name: Install MFEM
      run: brew install mfem

    - name: Call Build SLOTH Workflow
      uses: ./.github/workflows/sloth-compile-and-test.yml
      with:
        cores: ${{ env.CORES }}
        workspace: ${{ github.workspace }}

