name: Build and Test SLOTH on UNIX 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    env: 
      CORES: $(nproc)
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        gcc_version: [11, 14]
        exclude:
          - os: ubuntu-22.04
            gcc_version: 14  
          - os: ubuntu-24.04
            gcc_version: 11 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: ${{github.workspace}}/spack       # Where to clone Spack
    - name: Install MFEM
      run: |
        spack install mfem+mpi+suite-sparse+sundials+superlu-dist@4.7.0 %gcc@${{ matrix.gcc_version }}

    - name: Build SLOTH [Release]
      run: | 
        mkdir build
        cd build
        source ../envSloth.sh 
        make -j ${{env.CORES}}

  build-MacOS:
    runs-on: macos-latest
    env: 
      CORES: $(sysctl -n hw.ncpu)
    steps:
    - uses: actions/checkout@v4

    - name: Install Packages
      run: brew install mfem

    - name: Build SLOTH [Release]
      run: | 
        mkdir build
        cd build
        source ../envSloth.sh
        make -j ${{env.CORES}}