name: Build and Test SLOTH on Linux and MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    env: 
      CORES: $(nproc)
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-22.04, ubuntu-24.04]
        # gcc_version: [11, 14]
        # exclude:
        #   - os: ubuntu-22.04
        #     gcc_version: 14  
        #   - os: ubuntu-24.04
        #     gcc_version: 11 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: ${{github.workspace}}/spack       # Where to clone Spack
    - name: Install MFEM
      run: |
        spack install mfem+mpi+suite-sparse+sundials+superlu-dist@4.7.0

    - name: Build SLOTH 
      run: | 
        mkdir -p ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        bash ../envSloth.sh --coverage
        make -j${{ env.CORES }}
        
    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies 
      run: python -m pip install --upgrade pip gcovr cpplint matplotlib pandas numpy scipy

    - name: Test SLOTH 
      run: | 
        cd ${{ github.workspace }}/build
        ctest -j${{ env.CORES }} --output-on-failure

    - name: Archive test reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ${{ github.workspace }}/build/tests
        retention-days: 1

    - name: Code Coverage Analysis 
      if: ${{ always() }}
      run: | 
        cd ${{ github.workspace }}/build
        make cc

    - name: Archive code coverage results
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/build/Coverage/coverage.html
        retention-days: 1
  
    - name: Cpplint
      if: ${{ always() }}
      run: | 
        cd ${{ github.workspace }}/build
        make lint
      
  


  build-MacOS:
    runs-on: macos-latest
    env: 
      CORES: $(sysctl -n hw.ncpu)
    steps:
    - uses: actions/checkout@v4

    - name: Install MFEM
      run: brew install mfem
      
    - name: Build SLOTH 
      run: | 
        mkdir -p ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        bash ../envSloth.sh --coverage
        make -j${{ env.CORES }}

    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies 
      run: python -m pip install --upgrade pip gcovr cpplint matplotlib pandas numpy scipy

    - name: Test SLOTH 
      run: | 
        cd ${{ github.workspace }}/build
        ctest -j${{ env.CORES }} --output-on-failure

    - name: Archive test reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ${{ github.workspace }}/build/tests
        retention-days: 1

    - name: Code Coverage Analysis 
      if: ${{ always() }}
      run: | 
        cd ${{ github.workspace }}/build
        make cc
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ github.workspace }}/build/Coverage/coverage.xml
        badge: true
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both

    - name: Archive code coverage results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/build/Coverage
        retention-days: 1
  
    - name: Cpplint
      if: ${{ always() }}
      run: | 
        cd ${{ github.workspace }}/build
        make lint
    
