name: Build SLOTH 

on:
  workflow_call:
    inputs:
      CORES:
        description: "Number of cores for parallel compilation"
        required: true
        type: string
      workspace:
        description: "GitHub workspace directory"
        required: true
        type: string
      os:
        description: "Operating system for the runner"
        required: true
        type: string

jobs:
  build-sloth:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Build SLOTH 
      run: | 
        mkdir -p ${{ inputs.workspace }}/build
        cd ${{ inputs.workspace }}/build
        bash ../envSloth.sh --coverage
        make -j${{ inputs.CORES }}

    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies 
      run: python -m pip install --upgrade pip pandas numpy scipy

    - name: Test SLOTH 
      run: | 
        cd ${{ inputs.workspace }}/build
        ctest -j${{ inputs.CORES }}

    - name: Archive test reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ${{ inputs.workspace }}/build/tests
        retention-days: 1

    - name: Code Coverage Analysis 
      if: ${{ always() }}
      run: | 
        cd ${{ inputs.workspace }}/build
        make cc

    - name: Archive code coverage results
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ inputs.workspace }}/build/Coverage/coverage.html
        retention-days: 1