# .github/workflows/build-sloth.yml

name: Build SLOTH 

on:
  workflow_call:
    inputs:
      CORES:
        description: "Number of cores for parallel compilation"
        required: true
        type: string
      workspace:
        description: "GitHub workspace directory"
        required: true
        type: string

jobs:
  build-sloth:
    runs-on: ${{ github.event.inputs.os }}
    steps:
    - name: Build SLOTH 
      run: | 
        mkdir -p  ${{github.event.inputs.workspace}}/build
        cd ${{github.event.inputs.workspace}}/build
        bash ../envSloth.sh --coverage
        make -j ${{github.event.inputs.CORES}}

    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Python dependencies 
      run: python -m pip install --upgrade pip pandas numpy scipy

    - name: Test SLOTH 
      run: | 
        cd ${{github.workspace}}/build
        ctest -j ${{github.event.inputs.CORES}}

    - name: Archive tests
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: tests-report
        path: ${{github.event.inputs.workspace}}/build/tests
        retention-days: 1
    

    - name: Code Coverage Analysis 
      if: ${{ always() }}
      run: | 
        cd ${{github.event.inputs.workspace}}/build
        make cc

    - name: Archive code coverage results
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{github.event.inputs.workspace}}/build/Coverage/coverage.html
        retention-days: 1

